project:
  type: website

website:
  title: "IA"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - text: "Sesiones"  
        menu:
          - text: "Sesión 1"
          - href: s1.qmd
          - text: "Sesión 2"
          - href: s1.qmd

format:
  html:
    theme:
      - yeti
      - brand
    css: styles.css
    toc: true



